### ISSUE TITLE
这个和nvono有什么区别啊?

### ISSUE THREAD

**Issue by lersh** [bettermanbao/openwrt-shadowsocksR-libev-full#1]
https://github.com/nvono/openwrt-shadowsocks/tree/shadowsocksR
这个分支貌似还实现了透明代理和udp转发

**Comment by allenkey666** [comment]
透明代理和udp转发都是原版libev就支持的。

他这个fork最原始的版本是 @aa65535 的版本，里面 "-spec" 的衍生版是基于chinadns的国内国外分流。由于chinadns作者已经不再维护，所以DNS解析上有些bug也就无解了。

我的 "-gfwlist" 版本是基于GFW List的黑名单分流，不依赖其他任何软件，更稳定和轻巧。整套方案可以预编译进4M的固件内，实际使用中速度更快。

**Comment by lersh** [comment]
非常感谢
实际使用中，我其实也就用了ss-redir和ss-tunnel，然后是注释掉ss-rules，然后配合dnsmasq的ipset来做透明代理的，这样感觉可控性更高一点，但是不够智能，呵呵
