### ISSUE TITLE
多个服务器切换问题

### ISSUE THREAD

**Issue by sutun2008** [bettermanbao/openwrt-shadowsocksR-libev-full#10]
作者你好，我在三个vps，我想让他们轮流替换（当其中一个挂掉时）应如何实现？
我看到etc文件夹下有三个文件分别是shadowsocksr.json，shadowsocksr.json.backup，shadowsocksr.json.main分别设置成不同的服务端参数能实现轮流替换吗？

**Comment by allenkey666** [comment]
目前只支持main server挂了自动切换到backup server。只要把2个ss服务器信息填入main和backup文件内就可以了。

**Comment by sutun2008** [comment]
谢谢
