### ISSUE TITLE
2.4.5-6求编译BCM63XXX和MT7260

### ISSUE THREAD

**Issue by chobitsos** [bettermanbao/openwrt-shadowsocksR-libev-full#13]
发现有时候不知道什么原因，导致突然断流，ps了一下发现进程自动退出了，不知是否有BUG，添加了自启脚本之后发现无法自启，不知道什么原因！

**Comment by allenkey666** [comment]
mt7620一已编译，bcm63xx改天有空帮你编吧，之前的sdk删了。
