### ISSUE TITLE
2.4.5-6 如何添加gfwlist

### ISSUE THREAD

**Issue by xuefliang** [bettermanbao/openwrt-shadowsocksR-libev-full#14]
![qq 20160423164832](https://cloud.githubusercontent.com/assets/3095597/14760317/4ddb8da8-0973-11e6-9bc6-0a143cd62e46.png)
如图，新版中没有添加gfwlist，该如何添加？

**Comment by allenkey666** [comment]
显示的bug，最新的release已经修复。
