### ISSUE TITLE
请问2.4.5-6pre的gfwlist为空是什么情况，谢谢

### ISSUE THREAD

**Issue by Chandler-Lu** [bettermanbao/openwrt-shadowsocksR-libev-full#15]
请问2.4.5-6pre的gfwlist为空是什么情况，谢谢

**Comment by Chandler-Lu** [comment]
[2016-04-24 17:20:00] Network problem. Do nothing.
wget: invalid option -- 's'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
wget: invalid option -- 's'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
而且网络正常情况下提示这个

**Comment by allenkey666** [comment]
2个问题都已经修复，请重新下载2.4.5-6pre安装。
