### ISSUE TITLE
编译通过,安装时出现问题,求助

### ISSUE THREAD

**Issue by Biggulu** [bettermanbao/openwrt-shadowsocksR-libev-full#17]
Ubuntu16.04;
OpenWrt-SDK-15.05.1-bcm53xx_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2;
安装shadowsocksr-libev_2.4.5-6pre_bcm53xx.ipk正常
安装shadowsocksr-libev-gfwlist_2.4.5-6pre_bcm53xx.ipk提示

```
root@CRWsRouter:~# opkg install /tmp/shadw/shadowsocksr-libev-gfwlist_2.4.5-6pre_bcm53xx.ipk 
Installing shadowsocksr-libev-gfwlist (2.4.5-6pre) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocksr-libev-gfwlist:
 *      wget * 
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-gfwlist.
```

```
root@CRWsRouter:~# which wget
/usr/bin/wget
```

这是为什么呢?

**Comment by allenkey666** [comment]
opkg update一下，再装，如果还不行先装一下wget。
gfwlist版本自带的watchdog依赖gnu版的wget，op自带的busybox版的wget不行。

**Comment by allenkey666** [comment]
opkg update一下，再装，如果还不行先装一下wget。
gfwlist版本自带的watchdog依赖gnu版的wget，op自带的busybox版的wget不行。

**Comment by Biggulu** [comment]
重新安装wget搞定,非常感谢
