### ISSUE TITLE
想问一下是不是备份服务器配置有问题

### ISSUE THREAD

**Issue by Chandler-Lu** [bettermanbao/openwrt-shadowsocksR-libev-full#18]
我刚刚测试将主服务器和备份服务器改成完全一样的内容，在确定主服务器可用的情况下，把主服务器密码改成错误的，使软件切换成备份服务器，但是完全没法翻墙。

**Comment by allenkey666** [comment]
服务器切换是通过每10分钟运行一次的watchdog脚本触发的，不是实时切换的。
你修改主服务器文件后可以手动运行/root/ssr-watchdog，马上进行切换。切换成功会有log提示。

**Comment by chobitsos** [comment]
ssr-watchdog 这个脚本语法有些问题，根据我的测试wget -s -q -T 3 www.google.com.hk这句话存在问题
openwrt里面的wget -s(小写)是无效命令，需要手动改成wget -S -q -T 3 www.google.com.hk 才能正常执行

**Comment by allenkey666** [comment]
你看最新的源码，release里的源码没有更新。
