### ISSUE TITLE
安装dnsmasq-full的时候先卸载了openwrt自带的dnsmasq，一直连接不上

### ISSUE THREAD

**Issue by ocian** [bettermanbao/openwrt-shadowsocksR-libev-full#20]
### 安装过程

`root@OpenWrt:/tmp# opkg remove dnsmasq`
`Removing package dnsmasq from root...`
`Not deleting modified conffile /etc/dnsmasq.conf.`
`Not deleting modified conffile /etc/config/dhcp.`

`root@OpenWrt:/tmp# opkg install dnsmasq-full`
`Installing dnsmasq-full (2.73-1) to root...`
`Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/packages/base/dnsmasq-full_2.73-1_ar71xx.ipk.`
`Configuring dnsmasq-full.`
`Collected errors:`
`* resolve_conffiles: Existing conffile /etc/config/dhcp is different from the conffile in the new package. The new conffile will be placed at /etc/config/dhcp-opkg.`
### 结果

`[2016-05-03 05:50:00] Problem decteted, restarting ShadowsocksR...`
`[2016-05-03 06:00:00] Problem decteted, restarting ShadowsocksR...`
`[2016-05-03 06:10:00] Problem decteted, restarting ShadowsocksR...`
`[2016-05-03 06:20:00] Problem decteted, restarting ShadowsocksR...`
`[2016-05-03 06:30:00] Problem decteted, restarting ShadowsocksR...`

**Comment by allenkey666** [comment]
恢复出厂设置后运行readme里面下面两条命令安装，安装后确认可以访问google后，在修改SS的配置文件。
opkg update
opkg --force-overwrite install /tmp/shadowsocksr-libev-gfwlist*.ipk

**Comment by ocian** [comment]
`[2016-05-04 06:40:00] No Problem.`
但是打不开google.com  
电脑上使用命令  `ss-local` 配合foxyproxy   firefox可以正常访问
路由器通过pppoe协议连接校园网  这个有没有影响
路由器换用自己的ss代理配置还是一样无法访问google    ...这里，foxyproxy启用代理与不启用代理都试过
ShadowsocksR - Watchdog Log  `No Problem`

没有找到关于端口映射配置说明
在 Firewall - Custom Rules 最后面发现这三句
`ipset create gfwlist hash:ip`
`iptables -t nat -I PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080`
`iptables -t nat -I OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080`

已经重置 使用中科大的openwrt中转代理，
先使用命令 `scp` 传输安装包到路由器
然后按照上面的两条命令安装

请问还需要配置哪里    还是哪里又没有注意到

**Comment by allenkey666** [comment]
确认watchdog显示no problem，然后么电脑上用管理员权限运行一下ipconfig /flushdns就好了。
你这种情况比较像本机的dns缓存在shadowsocks正常运行前被污染了。

**Comment by ocian** [comment]
dns搞定了     圆满解决   谢谢

**Comment by WordlessEcho** [comment]
安装与卸载应该同步进行
```opkg remove dnsmasq && opkg install dnsmasq-full```

如果还是不慎卸载，你还有办法挽救：首先，dnsmasq 承担的是解析域名的角色，所以只需要想办法绕过域名解析就可以了

编辑 ```/etc/opkg/distfeeds.conf```，将 ```downloads.openwrt.org``` 替换为解析到的 IP 即可。

例如：在网络正常的机器上，执行 ping 到一个源：
```bash
ping downloads.openwrt.org
PING downloads.openwrt.org (xxx.xxx.xxx.xxx) : 56 data bytes

# Or USTC mirrors
ping mirrors.ustc.edu.cn
PING mirrors.ustc.edu.cn (xxx.xxx.xxx.xxx) : 56 data bytes
```
ping 会显示解析出的 IP，将其记下并替换即可

参考及致谢： [Shadowsocks + ChnRoute 实现 OpenWRT / LEDE 路由器自动翻墙](https://cokebar.info/archives/664)

**Comment by 1-bytes** [comment]
> 安装与卸载应该同步进行
> `opkg remove dnsmasq && opkg install dnsmasq-full`
> 
> 如果还是不慎卸载，你还有办法挽救：首先，dnsmasq 承担的是解析域名的角色，所以只需要想办法绕过域名解析就可以了
> 
> 编辑 `/etc/opkg/distfeeds.conf`，将 `downloads.openwrt.org` 替换为解析到的 IP 即可。
> 
> 例如：在网络正常的机器上，执行 ping 到一个源：
> 
> ```shell
> ping downloads.openwrt.org
> PING downloads.openwrt.org (xxx.xxx.xxx.xxx) : 56 data bytes
> 
> # Or USTC mirrors
> ping mirrors.ustc.edu.cn
> PING mirrors.ustc.edu.cn (xxx.xxx.xxx.xxx) : 56 data bytes
> ```
> 
> ping 会显示解析出的 IP，将其记下并替换即可
> 
> 参考及致谢： [Shadowsocks + ChnRoute 实现 OpenWRT / LEDE 路由器自动翻墙](https://cokebar.info/archives/664)

nice :)
