### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by woxinyi248** [bettermanbao/openwrt-shadowsocksR-libev-full#21]
备用服务器是直接添加到主服务器下面？   GFWList是自动更新还是手动更新 手动更新的操作命令是什么?      关闭是直接把启动项关闭？

**Comment by NOirBRight** [comment]
并没有提供修改备用服务器的luci界面（偶尔主服务器down的时候，会切过去，这时候可以编辑）。
要直接编辑的话，还是用putty把，在/etc/下，有3个shadowsocks配置文件，其中一个是切换用的，另外2个分别是主副服务器配置，直接填进去。

GFWlist并不会自动更新，需要手动更新，github里也有类似项目的，gfwlist直接转dnsmasq文件，需要在路由器上装python（非常占空间），然后你可以设置个计划任务定期去更新，然后转到对应目录去。

关闭也需要输命令：
/etc/init.d/shadowsocksr start       启动服务
/etc/init.d/shadowsocksr stop       停止服务
/etc/init.d/shadowsocksr restart    重启服务

**Comment by allenkey666** [comment]
@NOirBRight 朋友研究的很透彻嘛，其实gfwlist并不需要经常更新。
