### ISSUE TITLE
您好，我想问一下关于shadowsocks server在openwrt 上的部署

### ISSUE THREAD

**Issue by mao13820** [bettermanbao/openwrt-shadowsocksR-libev-full#22]
我按照您的ipk安装，安装完之后无法使用，提示segementation fault,我想问一下，是否是因为缺少一些库文件还是什么呢？因为我看有的教程需要连接一下路由的库，例如http://www.xuxiaobo.com/?p=629。谢谢您了

**Comment by allenkey666** [comment]
贴一下完整的log，我看看

**Comment by mao13820** [comment]
我在var/log里面好像没有看到log。。。。。
以下是我运行时的一些记录
Installing shadowsocks-libev-server (2.4.5-5) to root...
Configuring ip.
//usr/lib/opkg/info/ip.postinst: line 4: default_postinst: not found
Configuring resolveip.
//usr/lib/opkg/info/resolveip.postinst: line 4: default_postinst: not found
Configuring libpolarssl.
//usr/lib/opkg/info/libpolarssl.postinst: line 4: default_postinst: not found
Configuring zlib.
//usr/lib/opkg/info/zlib.postinst: line 4: default_postinst: not found
Configuring libopenssl.
//usr/lib/opkg/info/libopenssl.postinst: line 4: default_postinst: not found
Configuring shadowsocks-libev-server.
//usr/lib/opkg/info/shadowsocks-libev-server.postinst: line 4: default_postinst: not found
Collected errors:
- resolve_conffiles: Existing conffile /etc/shadowsocks-server.json is different from the conffile in the new package. The new conffile will be placed at /etc/shadowsocks-server.json-opkg.
- pkg_run_script: package "ip" postinst script returned status 127.
- opkg_configure: ip.postinst returned 127.
- pkg_run_script: package "resolveip" postinst script returned status 127.
- opkg_configure: resolveip.postinst returned 127.
- pkg_run_script: package "libpolarssl" postinst script returned status 127.
- opkg_configure: libpolarssl.postinst returned 127.
- pkg_run_script: package "zlib" postinst script returned status 127.
- opkg_configure: zlib.postinst returned 127.
- pkg_run_script: package "libopenssl" postinst script returned status 127.
- opkg_configure: libopenssl.postinst returned 127.
- pkg_run_script: package "shadowsocks-libev-server" postinst script returned status 127.
- opkg_configure: shadowsocks-libev-server.postinst returned 127.
  这是安装时候的记录
  root@CC:~# ss-server -s 0.0.0.0 -p 520 -k password -m aes-256-cfb
  2016-05-08 21:18:02 INFO: initialize ciphers... aes-256-cfb
  Segmentation fault
  这是我运行服务的时候的记录，显示segmentation fault，运行不了。。。。
  您看看是哪出问题了，谢谢了！

**Comment by allenkey666** [comment]
你是openwrt 14.07吧？预编译的ipk仅针对15.05

**Comment by mao13820** [comment]
谢谢您了，估计就是这个问题，我是attitude_adjustment，估计是12.09版本。但是这两天我试着自己去编译了一下，老是出问题。想请您看看这是为什么
humou@VM-69-84-debian:~/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2$ make package/shadowsocks-libev/compile V=99
tmp/.config-package.in:11:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev' refer to undefined symbol 'PACKAGE_libc'
tmp/.config-package.in:12:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev' refer to undefined symbol 'PACKAGE_libopenssl'
tmp/.config-package.in:13:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev' refer to undefined symbol 'PACKAGE_libpthread'
tmp/.config-package.in:14:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev' refer to undefined symbol 'PACKAGE_librt'
tmp/.config-package.in:15:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev' refer to undefined symbol 'PACKAGE_libpthread'
tmp/.config-package.in:25:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-polarssl' refer to undefined symbol 'PACKAGE_libc'
tmp/.config-package.in:26:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-polarssl' refer to undefined symbol 'PACKAGE_libpthread'
tmp/.config-package.in:27:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-polarssl' refer to undefined symbol 'PACKAGE_libpolarssl'
tmp/.config-package.in:28:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-polarssl' refer to undefined symbol 'PACKAGE_librt'
tmp/.config-package.in:29:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-polarssl' refer to undefined symbol 'PACKAGE_libpthread'
tmp/.config-package.in:39:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec' refer to undefined symbol 'PACKAGE_libc'
tmp/.config-package.in:40:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec' refer to undefined symbol 'PACKAGE_libopenssl'
tmp/.config-package.in:41:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec' refer to undefined symbol 'PACKAGE_ipset'
tmp/.config-package.in:42:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec' refer to undefined symbol 'PACKAGE_ip'
tmp/.config-package.in:43:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec' refer to undefined symbol 'PACKAGE_libpthread'
tmp/.config-package.in:44:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec' refer to undefined symbol 'PACKAGE_librt'
tmp/.config-package.in:45:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec' refer to undefined symbol 'PACKAGE_libpthread'
tmp/.config-package.in:55:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec-polarssl' refer to undefined symbol 'PACKAGE_libc'
tmp/.config-package.in:56:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec-polarssl' refer to undefined symbol 'PACKAGE_ipset'
tmp/.config-package.in:57:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec-polarssl' refer to undefined symbol 'PACKAGE_ip'
tmp/.config-package.in:58:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec-polarssl' refer to undefined symbol 'PACKAGE_libpthread'
tmp/.config-package.in:59:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec-polarssl' refer to undefined symbol 'PACKAGE_libpolarssl'
tmp/.config-package.in:60:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec-polarssl' refer to undefined symbol 'PACKAGE_librt'
tmp/.config-package.in:61:warning: 'select' used by config symbol 'PACKAGE_shadowsocks-libev-spec-polarssl' refer to undefined symbol 'PACKAGE_libpthread'
#

# using defaults found in .config

#

**\* End of OpenWrt configuration.
**\* Execute 'make' to build the OpenWrt or try 'make help'.

make[1]: Entering directory `/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2'
make[2]: Entering directory`/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/package/shadowsocks-libev'
(cd /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/build_dir/target-_-/shadowsocks-libev/openssl/shadowsocks-libev-2.4.6; rm -f aclocal.m4; if [ -f ./configure.ac ] || [ -f ./configure.in ]; then [ -d ./autom4te.cache ] && rm -rf autom4te.cache; [ -e ./config.rpath ] || ln -s /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/scripts/config.rpath ./config.rpath; touch NEWS AUTHORS COPYING ABOUT-NLS ChangeLog; AUTOM4TE=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/autom4te AUTOCONF=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/autoconf AUTOMAKE=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/automake ACLOCAL=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/aclocal AUTOHEADER=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/autoheader LIBTOOLIZE=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/libtoolize LIBTOOL=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/libtool M4=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/m4 AUTOPOINT=true /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/autoreconf -v -f -i -s -B /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/share/aclocal -I /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/host/share/aclocal -I /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/usr/share/aclocal -I m4 -I . . || true; fi; );
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/aclocal -I /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/host/share/aclocal -I /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/usr/share/aclocal -I m4 -I . --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory libsodium to autoreconf
autoreconf: Entering directory `libsodium'
autoreconf: running: /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/libtoolize --force
OpenWrt-libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR,`build-aux'.
OpenWrt-libtoolize: linking file `build-aux/ltmain.sh'
OpenWrt-libtoolize: putting macros in AC_CONFIG_MACRO_DIR,`m4'.
OpenWrt-libtoolize: linking file `m4/libtool.m4'
OpenWrt-libtoolize: linking file`m4/ltoptions.m4'
OpenWrt-libtoolize: linking file `m4/ltsugar.m4'
OpenWrt-libtoolize: linking file`m4/ltversion.m4'
OpenWrt-libtoolize: linking file `m4/lt~obsolete.m4'
autoreconf: running: /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/autoconf --include=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/host/share/aclocal --include=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/usr/share/aclocal --include=m4 --include=. --prepend-include=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/share/aclocal --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/automake --add-missing --force-missing
autoreconf: Leaving directory `libsodium'
OpenWrt-libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR,`auto'.
OpenWrt-libtoolize: linking file `auto/ltmain.sh'
OpenWrt-libtoolize: putting macros in AC_CONFIG_MACRO_DIR,`m4'.
OpenWrt-libtoolize: linking file `m4/libtool.m4'
OpenWrt-libtoolize: linking file`m4/ltoptions.m4'
OpenWrt-libtoolize: linking file `m4/ltsugar.m4'
OpenWrt-libtoolize: linking file`m4/ltversion.m4'
OpenWrt-libtoolize: linking file `m4/lt~obsolete.m4'
autoreconf: running: /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/autoheader --include=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/host/share/aclocal --include=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/usr/share/aclocal --include=m4 --include=. --prepend-include=/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/share/aclocal --force
autoreconf: Leaving directory `.'
(cd /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/build_dir/target-_-/shadowsocks-libev/openssl/shadowsocks-libev-2.4.6/./; if [ -x ./configure ]; then /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/find /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/build_dir/target-_-/shadowsocks-libev/openssl/shadowsocks-libev-2.4.6/ -name config.guess | xargs -r chmod u+w; /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/find /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/build_dir/target-_-/shadowsocks-libev/openssl/shadowsocks-libev-2.4.6/ -name config.guess | xargs -r -n1 cp /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/scripts/config.guess; /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/find /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/build_dir/target-_-/shadowsocks-libev/openssl/shadowsocks-libev-2.4.6/ -name config.sub | xargs -r chmod u+w; /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/host/bin/find /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/build_dir/target-_-/shadowsocks-libev/openssl/shadowsocks-libev-2.4.6/ -name config.sub | xargs -r -n1 cp /home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/scripts/config.sub; AR=-openwrt-linux-ar AS="-openwrt-linux-gcc -c  -fhonour-copts -Wno-error=unused-but-set-variable" LD=-openwrt-linux-ld NM=-openwrt-linux-nm CC="-openwrt-linux-gcc" GCC="-openwrt-linux-gcc" CXX="no" RANLIB=-openwrt-linux-ranlib STRIP=-openwrt-linux-strip OBJCOPY=-openwrt-linux-objcopy OBJDUMP=-openwrt-linux-objdump SIZE=-openwrt-linux-size CFLAGS=" -fhonour-copts -Wno-error=unused-but-set-variable " CXXFLAGS=" -fhonour-copts -Wno-error=unused-but-set-variable " CPPFLAGS="-I/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/usr/include -I/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/include -I/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/toolchain-_gcc-_-/usr/include -I/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/toolchain-_gcc-_-/include " LDFLAGS="-L/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/usr/lib -L/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/target-_-/lib -L/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/toolchain-_gcc-_-/usr/lib -L/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/staging_dir/toolchain-_gcc-_-/lib "   ./configure --target=-openwrt-linux --host=-openwrt-linux --build=i486-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  --disable-ipv6 --disable-ssp ; fi; )
checking for -openwrt-linux-gcc... -openwrt-linux-gcc
checking whether the C compiler works... no
configure: error: in `/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/build_dir/target-_-/shadowsocks-libev/openssl/shadowsocks-libev-2.4.6':
configure: error: C compiler cannot create executables
See`config.log' for more details
make[2]: **\* [/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/build_dir/target-_-/shadowsocks-libev/openssl/shadowsocks-libev-2.4.6/.configured_] Error 77
make[2]: Leaving directory `/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2/package/shadowsocks-libev'
make[1]: *** [package/shadowsocks-libev/compile] Error 2
make[1]: Leaving directory`/home/humou/OpenWrt-SDK-ar71xx-for-linux-i486-gcc-4.6-linaro_uClibc-0.9.33.2'
make: **\* [package/shadowsocks-libev/compile] Error 2
其中我看说详细信息在config.log里面，可是我没找到config.log...
谢谢您了！

**Comment by allenkey666** [comment]
为什么不升级15.05呢？AA我没试过编译，可能会缺失某些lib。

**Comment by mao13820** [comment]
主要是之前用的就是aa，担心升级后会出问题，因为现在用的挺稳定的。就没有升级。我是用的官方sdk编译的，但是不知道为什么老是出这个问题。之前有阵子我没注意我的固件型号，直接用最新版本的编译，也是这个错误。。。我换了ubuntu，debian，都这样。。。就是不知道为什么。。。我看上面那些提示显示我gcc有问题，可是我安装了gcc，也更新到最新了。。。

**Comment by allenkey666** [comment]
AA可能makefile不兼容吧，你什么路由？
我这个ipk编译进固件的话，在CC版下，只要4M + 32M就能稳定运行了。

**Comment by mao13820** [comment]
这是路由器型号TP-Link TL-WR741N/ND v4。cpu芯片是Atheros AR9330 rev 1

**Comment by allenkey666** [comment]
4M + 32M的配置？

**Comment by mao13820** [comment]
我看了一下，是8M的闪存，64M的内存

**Comment by allenkey666** [comment]
升级CC吧，这个配置CC绝对流畅。

**Comment by mao13820** [comment]
升级的话复杂吗？会有一些不兼容吗？因为我里面安装了很多乱七八糟的东西。。。。。

**Comment by allenkey666** [comment]
你备份一下，试看不就知道了

**Comment by mao13820** [comment]
弄了半天还是不行，不过谢谢你啦
