### ISSUE TITLE
watchdog 里面的代码啥意思

### ISSUE THREAD

**Issue by justingkao** [bettermanbao/openwrt-shadowsocksR-libev-full#26]
sh: backup: unknown operand
[2016-05-13 08:20:00] No problem.
sh: backup: unknown operand
[2016-05-13 08:30:00] No problem.
sh: backup: unknown operand
[2016-05-13 08:40:00] No problem.
sh: backup: unknown operand
[2016-05-13 08:50:00] No problem.
sh: backup: unknown operand
[2016-05-13 09:00:00] No problem.
sh: backup: unknown operand
[2016-05-13 09:10:00] No problem.
sh: backup: unknown operand
[2016-05-13 09:20:00] No problem.

sh: backup: unknown operand
啥意思  是我的配置文件有问题吗（可以正常翻墙）

**Comment by allenkey666** [comment]
请提供路由器型号，以及当前使用的固件。另外你是自己编译的，还是用我发布ipk？

**Comment by justingkao** [comment]
PHICOMM PSG1208/K1   OpenWrt Chaos Calmer 15.05.1 r49097 / LuCI for-15.05 branch (git-16.090.31416-605d1f1)  装的是你发布的ipk  我是从旧版本升级过来的

**Comment by allenkey666** [comment]
比较奇怪，你的watchdog修改过吗？
贴出来我看看吧

**Comment by justingkao** [comment]
没有修改过
#!/bin/sh

LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")

CURRENT=$(ls -l /etc/shadowsocksr.json | awk -F "." '{print $4}')

if [ $CURRENT == "backup" ]; then
    echo "[$LOGTIME] Backup server is running."
    MAIN=$(cat /etc/shadowsocksr.json.main | awk -F '\"' '/\"server\"/ {print $4}')
    PM=$(ping -c 3 $MAIN | grep 'loss' | awk -F ',' '{ print $3 }' | awk -F "%" '{ print $1 }')
    if [ "$PM" -lt "50" ]; then
        echo "[$LOGTIME] Main server up,$PM% packet loss, switch back."
        ln -sf /etc/shadowsocksr.json.main /etc/shadowsocksr.json
        CURRENT=$(ls -l /etc/shadowsocksr.json | awk -F "." '{print $4}')
        /etc/init.d/shadowsocksr restart
        sleep 3
    else
        echo "[$LOGTIME] Main server down,$PM% packet loss."
    fi
fi

wget --spider --quiet -T 3 www.google.com.hk
if [ "$?" == "0" ]; then
    echo "[$LOGTIME] No problem."
    exit 0
else
    wget --spider --quiet -T 3 www.baidu.com
    if [ "$?" == "0" ]; then
        echo "[$LOGTIME] Problem decteted, restart ShadowsocksR."
        /etc/init.d/shadowsocksr restart
        if [ $CURRENT == "main" ]; then
            sleep 3
            wget --spider --quiet -T 3 www.google.com.hk
            if [ "$?" == "0" ]; then
                echo "[$LOGTIME] ShadowsocksR recovered."
                exit 0
            else
                echo "[$LOGTIME] Main server down, switch to backup server."
                ln -sf /etc/shadowsocksr.json.backup /etc/shadowsocksr.json
                /etc/init.d/shadowsocksr restart
                exit 0
            fi
        fi
    else
        echo "[$LOGTIME] Network problem. Do nothing."
    fi
fi

**Comment by zongai** [comment]
同样问题，将 $CURRENT 改  “$CURRENT”  解决了

**Comment by allenkey666** [comment]
fixed.
