### ISSUE TITLE
大神能不能编译一个x86_64版本的openwrt-shadowsocksR-libev-full

### ISSUE THREAD

**Issue by mkiii** [bettermanbao/openwrt-shadowsocksR-libev-full#28]
> 我在centos6.5上尝试编译一个需求版本的ssr-libev，结果错误太多，一下子应付不过来.
> 大神能不能预编译一个x86_64的，解解燃眉之急？非常感谢！
> 我的固件版本
> chaos_calmer/15.05/x86/64/openwrt-15.05-x86-64-combined-ext4.img.gz
> Linux OpenWrt 3.18.20 #1 SMP Fri Sep 4 20:16:14 CEST 2015 x86_64 GNU/Linux

我已经自己编译了一个。

**Comment by mkiii** [comment]
但是我用openwrt-shadowsocksR-libev-full，上传不稳定，具体表现是延迟大，测速也不及原来的一半，我又用回了openwrt-shadowsocks-libev + ChinaDNS + Dnsmasq的组合，服务端还是SSR。

**Comment by allenkey666** [comment]
你有加混淆吗？

**Comment by mkiii** [comment]
加了，如果格式错误，是不是直接不通？

**Comment by allenkey666** [comment]
混淆会影响速度

**Comment by mkiii** [comment]
好吧..
