### ISSUE TITLE
请加入开关按钮,和多服务器切换,比如几个jason.

### ISSUE THREAD

**Issue by genics** [bettermanbao/openwrt-shadowsocksR-libev-full#29]
最好还有运行状态显示,另外路由开ss总感觉比pc客户端慢,能否优化下?详细请看这个文章.
http://www.91yun.org/archives/1068

**Comment by allenkey666** [comment]
梅林的方案确实会影响网速，但一般只在浏览网页时能够感觉到。
我的方案理论上对网速完全没有影响，并且已经对openwrt做过优化，特别是浏览网页时的速度。
