### ISSUE TITLE
能否支持UDP over TCP功能

### ISSUE THREAD

**Issue by lersh** [bettermanbao/openwrt-shadowsocksR-libev-full#3]
今天发现公司的网络，DNS解析会间歇性的无响应，我自己配置了一台VPS做DNS解析，也会间歇性无响应，无响应期间再另一台VPS上dig我自己的VPS是可以正常返回的。用了ss-tunnel做UDP转发也不行，因此我试想是不是可以用TCP来转发UDP做DNS解析，不知道shadowsocks-libev是否支持？

**Comment by allenkey666** [comment]
如果纯粹为了防止dns污染，可以直接用opendns的dns-crypt解决。
ss-tunnel可以直接做udp隧道。

**Comment by lersh** [comment]
ss-tunnel不行，会间歇性的被阻断。dns-crypt我看看是啥…没用过。破娃酱的c#客户端实现了udp over tcp ，希望shadowsocks-libev也能实现吧…

**Comment by lersh** [comment]
看了下dns-crypt，应该不满足我的需求，首先我想在路由器上实现，其次公司的部分内外站点需要用公司的dns解析，这个dns-cyrpt估计做不到

**Comment by allenkey666** [comment]
ssr-tunnel -c $CONFIG -b 0.0.0.0 -l 5353 -L 8.8.8.8:53 -U
5353是隧道回本地的UDP监听端口
8.8.8.8:53换成你ss服务器端的dns ip
配置文件里面把混淆打开，肯定可以稳定的把dns隧道到本地的。
这样你和ss服务器间是tcp通信，但建立的隧道是UDP的。

**Comment by allenkey666** [comment]
我的gfwlist方案就是用ssr-tunnel把dns请求隧道到ss服务器端的，实测即使不加混淆也非常稳定。

**Comment by lersh** [comment]
ssr-tunnel -c $CONFIG -b 0.0.0.0 -l 5353 -L 8.8.8.8:53 -U 我就是这样配置的，但是用dig测试，有时能用有时不能用，不能用时，直接dig @8.8.8.8也是不通的，换成我自己的vps的ip也是不通的。ss-tunnel只是建立了udp通道，因此我怀疑是公司的网络会间歇性的阻断udp的链接。

**Comment by lersh** [comment]
这个dns解析失败确实不常见，我在家庭网络里都是正常的，但是在公司里就是间歇性有问题。

**Comment by lersh** [comment]
折腾了下，用pdnsd实现了tcp查询dns，并用ss-redir混淆pdnsd的数据实现了防污染的功能……
