### ISSUE TITLE
newifi openwrt build 1024 已经具备wget功能，但是还是提示缺少wget依赖

### ISSUE THREAD

**Issue by j4Uq** [bettermanbao/openwrt-shadowsocksR-libev-full#30]
![default](https://cloud.githubusercontent.com/assets/6436073/15696624/b4647096-27e4-11e6-8c8f-47d349375779.png)

**Comment by allenkey666** [comment]
你这个wget缺少-T参数。

**Comment by j4Uq** [comment]
![default](https://cloud.githubusercontent.com/assets/6436073/15769279/2a50f4f2-298c-11e6-96d0-63a55249a0f3.png)

**Comment by allenkey666** [comment]
从未用过Pandora固件，所以不太了解。
