### ISSUE TITLE
望编译WRT1900ACS的IPK

### ISSUE THREAD

**Issue by Turing-Wu** [bettermanbao/openwrt-shadowsocksR-libev-full#31]
WRT1900AC的玩家也挺多的。也是目前OpenWrt官方支持的最高端的路由器型号。

**Comment by allenkey666** [comment]
readme有提供编译方法，你都玩那么高端的路由了，自己编译应该不成问题吧？

**Comment by Turing-Wu** [comment]
我目前用AR9344的入门级路由，水平也就会刷官方固件再安装ipk而已。想入个高端路由，但是并不是入了高端路由就能变成高手...... 看来还是老老实实玩入门级路由算了 ^_^
