### ISSUE TITLE
能否增加一个局域网设备的排除功能

### ISSUE THREAD

**Issue by NOirBRight** [bettermanbao/openwrt-shadowsocksR-libev-full#32]
局域网中有一些设备翻墙后，运行不太正常。
比如ps4的市场里，路由翻墙后，有一些主题无法下载，好像是我vps的ip在psn的黑名单中。
还有比如说在pc上，我路由翻墙后，无法使用finalspeed来加速了。

是否可以考虑增加一个局域网设备的排除功能，指定ip后，这个设备就直接连接，不再翻墙?

**Comment by allenkey666** [comment]
修改下面这条iptables，可以指定只转发某个网段的流量，这样PS4手动指定IP，在网段外就可以了。
iptables -t nat -I PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080

**Comment by NOirBRight** [comment]
折腾了下，基本搞定了，把过程写下来供其他人参考。
排除局域网IP，最好改写下firewall.user，具体如下：

#原本就自带的ipset命令，用来判断目标ip是否是黑名单
ipset create gfwlist hash:ip

#由于要加入排除的过程，所以新建一个fuckgfw的chain，用来逐一排除
iptables -N fuckgfw -t nat

#下面这个命令会排除局域网ip为192.168.199.2的设备在翻墙设备列表之外，需要排除其他设备的复制这条命令并修改，每行一个ip
iptables -A fuckgfw -t nat -p tcp -s 192.168.199.2 -j RETURN

#排除特定的设备后，剩下的设备全部翻墙
iptables -A fuckgfw -t nat -p tcp -j REDIRECT --to-port 1080

#原本就自带的命令，第一个用于翻墙，第二个用户watchdog的服务器状态跟踪，都需要保留，只是原本直接转发端口了，现在进入fuckgfw的chain中进行判断来排除特定的ip。
iptables -A PREROUTING -t nat -p tcp -m set --match-set gfwlist dst -j fuckgfw
iptables -A OUTPUT  -t nat -p tcp -m set --match-set gfwlist dst -j fuckgfw
