### ISSUE TITLE
ssr-redir是否支持-u启动udp的代理

### ISSUE THREAD

**Issue by NOirBRight** [bettermanbao/openwrt-shadowsocksR-libev-full#33]
主要是PS4联机的时候会用到udp的代理，ssr-redir是否可以像ss-redir那样，加-u参数使用？

**Comment by allenkey666** [comment]
可以，你自己加上去就可以了。因为gfwlist方案主要是针对网页浏览的，所以没有开udp。

**Comment by NOirBRight** [comment]
测试成功了，过程写下留个档。

1、要实现udp转发，还需要手动安装一些ipk，具体过程如下：
opkg update
opkg install iptables-mod-tproxy kmod-ipt-tproxy ip iptables-mod-geoip

2、修改/etc/init.d/shadowsocksr，打开ssr-redir的udp转发功能。注意这也需要服务器的ss服务器配置打开了udp转发，否则整个这篇内容都是无用功。
service_start /usr/bin/ssr-redir -c $CONFIG -b 0.0.0.0 -l 1080
修改为
service_start /usr/bin/ssr-redir -u -c $CONFIG -b 0.0.0.0 -l 1080

修改后，重启下ssr
/etc/init.d/shadowsocksr restart

3、由于游戏需要加速主要原因是直接访问速度慢，而不是目标地址在墙后，所以再使用gfwlist就不太合适了，参考：https://0066.in/archives/568 的教程，使用iptables-mod-geoip的模块，来判断目标ip是否是大陆ip，如果不是则翻墙，类似于大陆白名单模式，由于这个只涉及到udp的特定端口转发，所以不会影响到平时的gfwlist的tcp翻墙。具体如下：
mkdir -p /usr/share/xt_geoip/LE
mkdir -p /usr/share/xt_geoip/BE
wget http://down.0066.in/openwrt/geoip/LE/CN.iv4 -O /usr/share/xt_geoip/LE/CN.iv4
wget http://down.0066.in/openwrt/geoip/BE/CN.iv4 -O /usr/share/xt_geoip/BE/CN.iv4

4、修改firewall.user，在最后添加如下内容：
#UDP CN白名单模式
#UDP转发需要用到mangle表，所以在mangle表里新增一个gameboost链
iptables -N gameboost -t mangle

#标记IP段，具体有啥用我也不知道，但我看到所有udp转发的教程里都有这两行，所以也加上了。
#ip命令在原版openwrt并不包含，需要opkg自己安装，已经在第一点里写出。
ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100

#判断目标ip是否大陆IP，如果是，则跳出链，直接连接
iptables -t mangle -A gameboost -m geoip -p udp --destination-country CN -j RETURN

#测试下来如果全局的UDP端口都打开了转发，会导致PS4无法联网，所以只需要打开特定的PSN及联网所需要的UDP端口即可，即--dport所指向的端口，每行一个，需要别的也可执行添加。当目标端口是以下这些的时候，选择代理连接。需要iptables的tproxy模块支持，已经在第一点里写出。
iptables -t mangle -A gameboost -p udp --dport 443 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
iptables -t mangle -A gameboost -p udp --dport 1935 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
iptables -t mangle -A gameboost -p udp --dport 3074:3075 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
iptables -t mangle -A gameboost -p udp --dport 3478:3480 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
iptables -t mangle -A gameboost -p udp --dport 3658:3659 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01
iptables -t mangle -A gameboost -p udp --dport 6000 -j TPROXY --on-port 1080 --tproxy-mark 0x01/0x01

#同样UDP转发可能带来网络的不稳定，还有会影响到P2P的下载（P2P大部分使用UDP端口，万一和你设置的那些端口重合，会导致你翻墙来下载P2P，很可能会导致SS账号被封停）。故建议只把需要使用到UDP转发的设备添加到链里即可。
#这里两个IP一个是我的PS4，另一个是我的PC。之所以要添加PC是因为为了测试整个设置是否生效，验证方式在之后的第五点中会给出。测试完成后，PC的IP就可以删除了。
iptables -t mangle -A PREROUTING -s 192.168.199.148 -j gameboost
iptables -t mangle -A PREROUTING -s 192.168.199.181 -j gameboost

#至此，firewall.user的修改全部结束，修改完毕后，记得重启firewall。最好用命令行重启，这样能观察到有哪些报错，从而进一步修改。
/etc/init.d/firewall restart

5、验证设置是否生效。
下载nattypetester（PC版），下载地址自己搜索把。
打开软件后，直接点击Get，观察Public End的IP地址，如果是ss服务器的地址，说明转发生效。如果是你本地网络的地址，说明转发无效，再检查一下之前各环节的设置是否正确。

**Comment by allenkey666** [comment]
为什么不针对ps4的mac地址写一条全局转发的iptables规则？然后ss-redir加个-u参数就可以了。

**Comment by NOirBRight** [comment]
不知道为啥，全局转发就不能上网了。
可能和5353的端口冲突？

**Comment by allenkey666** [comment]
全局转发的时候要排除路由器ip，否则dns会不能解析

**Comment by genics** [comment]
bettermanbao写个教程吧，我还以为默认ssr就已经支持游戏udp转发了，还用了那么久。。。

**Comment by genics** [comment]
NOirBRight 能留个联系方式吗?我按照你的方法做了,udp能获得ss的ip了,但是上不了网了,pc不能获得ip.不知道是不是和mwan3多拨有关,应为多拨里面也有iptables规则.

**Comment by genics** [comment]
删除mwan3后,问题解决.不知道能不能和mwan3兼容.

**Comment by allenkey666** [comment]
mwan3需要增加一条所有匹配gfwlist的ipset的流量走default路由的规则。

**Comment by genics** [comment]
太难了,才学习了一下iptables,还是搞不来.

**Comment by genics** [comment]
请问是这样设置吗?
![image](https://cloud.githubusercontent.com/assets/18501759/16953132/78dcbac0-4dfe-11e6-9392-da7e82fb85af.png)

**Comment by genics** [comment]
经测试,上面设置没有问题,留下给需要的朋友,

**Comment by allenkey666** [comment]
其实不用填源地址，ipset填gfwlist，policy选default，这样只要一条规则就可以匹配所有设备了。
另外建议再加一条端口443的流量勾选sticky，否则登陆网银会报错。

**Comment by genics** [comment]
因为我有电信联通两条线.所以有wan_only 和wan2_only. 默认电脑和ps4用的其中一条,其他设备则是default的多线.所以没有设置443端口,因为是单线用电脑,所以网银目前没问题.谢谢提醒.

**Comment by zasl** [comment]
能否有简化的方法？luci能做到吗？

**Comment by leviacn** [comment]
为什么不针对ps4的mac地址写一条全局转发的iptables规则？然后ss-redir加个-u参数就可以了.
这个该怎么写呢？只让家里的电视翻过中移动的p2p限制。
