### ISSUE TITLE
请问支持openwrt 15.05.1 x86_64平台么？

### ISSUE THREAD

**Issue by tarkky** [bettermanbao/openwrt-shadowsocksR-libev-full#34]
您好，请问您的SSR, 可以安装在openwrt x_64 平台上面吗？我现在装的是原版+chinadns+dnsmasq，是直接升级还是要卸载原版？

**Comment by allenkey666** [comment]
x64需要你自己编译，方法见readme。
原来的软件全部卸载，最好能在原始的openwrt固件上安装，否则容易产生冲突。
