### ISSUE TITLE
增加一个   /etc/init.d/shadowsocksr   status 命令就好了

### ISSUE THREAD

**Issue by hwypengsir** [bettermanbao/openwrt-shadowsocksR-libev-full#35]
root@OpenWrt:~#  /etc/init.d/shadowsocksr
Syntax: /etc/init.d/shadowsocksr [command]

Available commands:
    start   Start the service
    stop    Stop the service
    restart Restart the service
    reload  Reload configuration files (or restart if that fails)
    enable  Enable service autostart
    disable Disable service autostart

增加一个   /etc/init.d/shadowsocksr   status 命令就好了

**Comment by allenkey666** [comment]
这个status不准的，他只能告诉你ssr是否正在运行。
如果希望看到ssr与服务器是否正常连通，可以查看/ver/log/shadowsocksr_watchdog.log文件。
