### ISSUE TITLE
如何编译一个适用于pandorabox固件的版本？

### ISSUE THREAD

**Issue by BROBIRD** [bettermanbao/openwrt-shadowsocksR-libev-full#40]
如题，看见论坛上有人发布了适用于潘多拉固件的ipk包，请问应该怎么自己编译它？

**Comment by allenkey666** [comment]
潘多拉没有研究过

**Comment by BROBIRD** [comment]
不知道 jc天马行空 用的是什么样的环境……您可以问一下他？

**Comment by Chandler-Lu** [comment]
就是用pandora的sdk直接编译就好了。。在pandora上安装也可以修改opkg.conf文件，然后装op的版本，在15.05上可用

**Comment by BROBIRD** [comment]
@ltr970503 然而并没找到Pandorabox的SDK……而且具体opkg.conf应该怎么改？

**Comment by allenkey666** [comment]
直接用OpenWrt BB的SDK编译即可。
