### ISSUE TITLE
请教个问题。

### ISSUE THREAD

**Issue by hkvsak** [bettermanbao/openwrt-shadowsocksR-libev-full#41]
请问如何在你的crontabs上加一个断线自动重启网络或路由器啊，脚本该怎么写啊！
小区的网络有时会掉线  -- 烂路由不会自动连！

**Comment by allenkey666** [comment]
network problem那行后面增加一条reboot命令就可以了

**Comment by hkvsak** [comment]
请问加个尝试3次，如果写啊！

**Comment by hkvsak** [comment]
请教博主，计划任务：尝试重启wan口，并限制重启失败尝试不超过3次，这样的脚本怎么写那，小白一个，能给写出来吗？

2016-07-12 9:08 GMT+08:00 bettermanbao <notifications@github.com>:
