### ISSUE TITLE
finaspeed加速ssr的问题

### ISSUE THREAD

**Issue by hangaj** [bettermanbao/openwrt-shadowsocksR-libev-full#44]
openwrt跑的debian运行的finaspeed，给openwrt运行的ssr客户端加速，finaspeed用的是udp加速，用电脑端的ssr客户端能用，openwrt上的用不了，直接填服务器地址能用，finaspeed加速服务器地址填127.0.0.1,求大神赐教

**Comment by allenkey666** [comment]
finalspeed只能加速TCP协议，这个版本的SSR用到了UDP协议解析DNS，所以配合finalspeed用不行。
最简单的是修改DNS解析的ss-tunnel为pdnsd，让把UDP协议的dns请求转换成TCP形式。

**Comment by hangaj** [comment]
好的，感谢抽空回答
