### ISSUE TITLE
建议采用SSR+ChnRoute 

### ISSUE THREAD

**Issue by xuefliang** [bettermanbao/openwrt-shadowsocksR-libev-full#5]
gfwlist需要手动写Custom List

**Comment by allenkey666** [comment]
ChinaDNS因为运行久了DNS解析会不正常，所以我个人不太喜欢用。而且dnsmasq嵌套ChinaDNS，如果chinadns的上游DNS再连接SS的，这样对域名解析速度影响很大。你如果喜欢ChinaDNS，完全可以安装SSR-libev原版客户端，然后自己配置ChinaDNS等。

另外，GFWList的一键安装包已经集成GFWList，Custom_List的作用只是方便用户自己增加额外需要走SS的域名。

**Comment by Ardentwheel** [comment]
Pcap_DNSProxy也不错，
支持Tcp_fast_open；
支持国内外分区请求；
同一请求都多次发送，
同时请求主服务器和备用服务器；

我用极2，使用时cpu占用在小于10%很流畅。就是对于一些cpu，负载可能太高
有编译后的ipk下载了
https://github.com/wongsyrone/openwrt-Pcap_DNSProxy

**Comment by allenkey666** [comment]
有空研究下

**Comment by allenkey666** [comment]
今天试了一下只装shadowsocks一个软件完成，完成dns防污染和国内国外自动分流，非常稳定。
看来可以做成一键安装包推广了。

**Comment by 88922493** [comment]
能不能做一个 SSR-ChinaDNS + 自动切换   的一键包。  或者指点一下怎么 手工配置这3个。  我的一些应用在 GWFlist下不常，在ChinaDNS下才能正常使用。
