### ISSUE TITLE
请问何时支持新的认证协议和混淆插件呢

### ISSUE THREAD

**Issue by zhongheng666** [bettermanbao/openwrt-shadowsocksR-libev-full#52]
目前服务器端用的auth_sha1_v2协议和tls1.2_ticket_auth混淆，使用非常稳定，但是目前发现只有shadowsockrocket支持最新的协议和混淆插件，路由器上就用不了了，不想改其他协议，毕竟得到一个好点的IP不容易。请问什么时候可以支持最新的协议和插件呢

**Comment by Kevin-KD** [comment]
同求更新，现在路由上搭建的SSR Server不支持新的协议

**Comment by allenkey666** [comment]
v20170521已更新
