### ISSUE TITLE
有沒有 OpenWrt Barrier Breaker 14.07 可用的版本呀？

### ISSUE THREAD

**Issue by weiyu99** [bettermanbao/openwrt-shadowsocksR-libev-full#53]
我有一個 14.07 openwrt 的路由放在國外，想在上面安裝 ssr-server。
我試著 compile 但是報錯了...

checking for mips-openwrt-linux-gcc... ccache_cc
checking whether the C compiler works... no
configure: error: in `/home/dennis/14/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.4.5':
configure: error: C compiler cannot create executables
See`config.log' for more details

**Comment by allenkey666** [comment]
ssr-server
