### ISSUE TITLE
CENTOS6.8无法编译x86_64版本

### ISSUE THREAD

**Issue by robinhoo1973** [bettermanbao/openwrt-shadowsocksR-libev-full#57]
在CentOS6.8 64bit版本上无法顺利编译，出错信息如下：
`configure: loading site script /root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/site/x86_64
checking for x86_64-openwrt-linux-gcc... ccache_cc
checking whether the C compiler works... no
configure: error: in `/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.4.5':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[2]: *** [/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.4.5/.configured_yyn] Error 77
make[2]: Leaving directory `/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/package/shadowsocksR-libev-full'
make[1]: *** [package/shadowsocksR-libev-full/compile] Error 2
make[1]: Leaving directory `/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'
make: *** [package/shadowsocksR-libev-full/compile] Error 2
`
具体的config.log如下:
`This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by shadowsocks-libev configure 2.4.5, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --buil
d=x86_64-redhat-linux --program-prefix= --program-suffix= --prefix=/usr --exec-p
refix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconf
dir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/
usr/info --disable-nls --disable-ssp

## --------- ##

hostname = localhost.localdomain
uname -m = x86_64
uname -r = 2.6.32-642.6.2.el6.centos.plus.x86_64
uname -s = Linux
uname -v = #1 SMP Wed Oct 26 06:49:20 UTC 2016

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64
/staging_dir/target-x86_64_uClibc-0.9.33.2/host/bin
PATH: /root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64
/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/bin
PATH: /root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64
/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/bin
PATH: /root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64
/staging_dir/host/bin
PATH: /root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64
/staging_dir/host/bin
PATH: /var/maven/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /sbin
PATH: /bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /opt/jdk1.8.0_92/bin
PATH: /opt/jdk1.8.0_92/jre/bin
PATH: /root/bin

## ----------- ##

configure:2330: loading site script /root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linar
o_uClibc-0.9.33.2.Linux-x86_64/include/site/x86_64
| #!/bin/sh
| . $TOPDIR/include/site/linux
| ac_cv_c_littleendian=${ac_cv_c_littleendian=yes}
| ac_cv_c_bigendian=${ac_cv_c_bigendian=no}
|
| ac_cv_sizeof___int64=0
| ac_cv_sizeof_char=1
| ac_cv_sizeof_int=4
| ac_cv_sizeof_int16_t=2
| ac_cv_sizeof_int32_t=4
| ac_cv_sizeof_int64_t=8
| ac_cv_sizeof_long_int=8
| ac_cv_sizeof_long_long=8
| ac_cv_sizeof_long=8
| ac_cv_sizeof_off_t=8
| ac_cv_sizeof_short_int=2
| ac_cv_sizeof_short=2
| ac_cv_sizeof_size_t=8
| ac_cv_sizeof_ssize_t=8
| ac_cv_sizeof_u_int16_t=2
| ac_cv_sizeof_u_int32_t=4
| ac_cv_sizeof_u_int64_t=8
| ac_cv_sizeof_uint16_t=2
| ac_cv_sizeof_uint32_t=4
| ac_cv_sizeof_uint64_t=8
| ac_cv_sizeof_unsigned_int=4
| ac_cv_sizeof_unsigned_long=8
| ac_cv_sizeof_unsigned_long_long=8
| ac_cv_sizeof_unsigned_short=2
| ac_cv_sizeof_void_p=8
configure:2471: checking for x86_64-openwrt-linux-gcc
configure:2498: result: ccache_cc
configure:2767: checking for C compiler version
configure:2776: ccache_cc --version >&5
/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/stagi
ng_dir/host/bin/ccache_cc: line 2: exec: ccache: not found
configure:2787: $? = 127
configure:2776: ccache_cc -v >&5
/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/stagi
ng_dir/host/bin/ccache_cc: line 2: exec: ccache: not found
configure:2787: $? = 127
configure:2776: ccache_cc -V >&5
/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/stagi
ng_dir/host/bin/ccache_cc: line 2: exec: ccache: not found
configure:2787: $? = 127
configure:2776: ccache_cc -qversion >&5
/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/stagi
ng_dir/host/bin/ccache_cc: line 2: exec: ccache: not found
configure:2787: $? = 127
configure:2807: checking whether the C compiler works
configure:2829: ccache_cc -Os -pipe -fno-caller-saves -fhonour-copts -Wno-error=
unused-but-set-variable  -I/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-
0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/usr/include -I/r
oot/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/include -I/root/OpenWrt-SDK-15.05-x86-64_gcc-
4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-lin
aro_uClibc-0.9.33.2/usr/include -I/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_
uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-
0.9.33.2/include  -L/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.
2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/usr/lib -L/root/OpenWrt
-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target
-x86_64_uClibc-0.9.33.2/lib -L/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uCli
bc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.
33.2/usr/lib -L/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Lin
ux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/lib  conft
est.c  >&5
/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/stagi
ng_dir/host/bin/ccache_cc: line 2: exec: ccache: not found
configure:2833: $? = 127
configure:2871: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "shadowsocks-libev"
| #define PACKAGE_TARNAME "shadowsocks-libev"
| #define PACKAGE_VERSION "2.4.5"
| #define PACKAGE_STRING "shadowsocks-libev 2.4.5"
| #define PACKAGE_BUGREPORT "max.c.lv@gmail.com"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:2876: error: in `/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-
0.9.33.2.Linux-x86_64/build_dir/target-x86_64_uClibc-0.9.33.2/shadowsocksR-libev
-openssl/shadowsocksR-libev-2.4.5':
configure:2878: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_c_bigendian=no
ac_cv_c_gettext_without_libintl=yes
ac_cv_c_littleendian=yes
ac_cv_c_long_double=no
ac_cv_conv_longlong_to_float=yes
ac_cv_env_CC_set=set
ac_cv_env_CC_value=ccache_cc
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-Os -pipe -fno-caller-saves -fhonour-copts -Wno-error=un
used-but-set-variable '
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value='-I/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc
-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/usr/include -I/
root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/stagin
g_dir/target-x86_64_uClibc-0.9.33.2/include -I/root/OpenWrt-SDK-15.05-x86-64_gcc
-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-li
naro_uClibc-0.9.33.2/usr/include -I/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro
_uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc
-0.9.33.2/include '
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-L/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-
0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/usr/lib -L/root/
OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir
/target-x86_64_uClibc-0.9.33.2/lib -L/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uCli
bc-0.9.33.2/usr/lib -L/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.3
3.2.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/lib
 '
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=set
ac_cv_env_build_alias_value=x86_64-redhat-linux
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=x86_64-openwrt-linux
ac_cv_env_target_alias_set=set
ac_cv_env_target_alias_value=x86_64-openwrt-linux
ac_cv_file__dev_zero=yes
ac_cv_func___adjtimex=yes
ac_cv_func___va_copy=no
ac_cv_func__exit=yes
ac_cv_func_bcmp=yes
ac_cv_func_bcopy=yes
ac_cv_func_bzero=yes
ac_cv_func_cimag=yes
ac_cv_func_creal=yes
ac_cv_func_fchmod=yes
ac_cv_func_getaddrinfo=yes
ac_cv_func_getcwd=yes
ac_cv_func_getdomainname=yes
ac_cv_func_getpgrp_void=yes
ac_cv_func_getpwuid_r=yes
ac_cv_func_gettimeofday=yes
ac_cv_func_index=yes
ac_cv_func_lstat=yes
ac_cv_func_lstat_dereferences_slashed_symlink=yes
ac_cv_func_lstat_empty_string_bug=no
ac_cv_func_malloc_0_nonnull=yes
ac_cv_func_malloc_works=yes
ac_cv_func_memcmp_clean=yes
ac_cv_func_memcmp_working=yes
ac_cv_func_posix_getgrgid_r=yes
ac_cv_func_posix_getpwuid_r=yes
ac_cv_func_psignal=yes
ac_cv_func_pthread_key_delete=yes
ac_cv_func_realloc_0_nonnull=yes
ac_cv_func_realloc_works=yes
ac_cv_func_rename=yes
ac_cv_func_rindex=yes
ac_cv_func_setgrent_void=yes
ac_cv_func_setlocale=yes
ac_cv_func_setpgrp_void=yes
ac_cv_func_setresuid=no
ac_cv_func_setvbuf_reversed=no
ac_cv_func_stat_empty_string_bug=no
ac_cv_func_stat_ignores_trailing_slash=no
ac_cv_func_strerror=yes
ac_cv_func_strftime=yes
ac_cv_func_utimes=yes
ac_cv_func_va_copy=no
ac_cv_func_vsnprintf=yes
ac_cv_have_accrights_in_msghdr=no
ac_cv_have_broken_snprintf=no
ac_cv_have_control_in_msghdr=yes
ac_cv_have_decl_sys_siglist=no
ac_cv_have_openpty_ctty_bug=yes
ac_cv_have_space_d_name_in_struct_dirent=yes
ac_cv_header_netinet_sctp_h=no
ac_cv_header_netinet_sctp_uio_h=no
ac_cv_int64_t=yes
ac_cv_lbl_unaligned_fail=no
ac_cv_linux_kernel_pppoe=yes
ac_cv_linux_vers=2
ac_cv_pack_bitfields_reversed=yes
ac_cv_path_LDCONFIG=
ac_cv_prog_CC=ccache_cc
ac_cv_regexec_segfault_emptystr=no
ac_cv_sctp=no
ac_cv_sizeof___int64=0
ac_cv_sizeof_char=1
ac_cv_sizeof_int16_t=2
ac_cv_sizeof_int32_t=4
ac_cv_sizeof_int64_t=8
ac_cv_sizeof_int=4
ac_cv_sizeof_long=8
ac_cv_sizeof_long_int=8
ac_cv_sizeof_long_long=8
ac_cv_sizeof_off_t=8
ac_cv_sizeof_short=2
ac_cv_sizeof_short_int=2
ac_cv_sizeof_size_t=8
ac_cv_sizeof_ssize_t=8
ac_cv_sizeof_u_int16_t=2
ac_cv_sizeof_u_int32_t=4
ac_cv_sizeof_u_int64_t=8
ac_cv_sizeof_uint16_t=2
ac_cv_sizeof_uint32_t=4
ac_cv_sizeof_uint64_t=8
ac_cv_sizeof_unsigned_int=4
ac_cv_sizeof_unsigned_long=8
ac_cv_sizeof_unsigned_long_long=8
ac_cv_sizeof_unsigned_short=2
ac_cv_sizeof_void_p=8
ac_cv_sys_restartable_syscalls=yes
ac_cv_time_r_type=POSIX
ac_cv_type_suseconds_t=yes
ac_cv_uchar=no
ac_cv_uint64_t=yes
ac_cv_uint=yes
ac_cv_ulong=yes
ac_cv_ushort=yes
ac_cv_va_copy=C99
ac_cv_va_val_copy=yes
as_cv_unaligned_access=yes

## ----------------- ##

ACLOCAL=''
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR=''
AM_BACKSLASH=''
AM_DEFAULT_V=''
AM_DEFAULT_VERBOSITY=''
AM_V=''
AR='x86_64-openwrt-linux-uclibc-gcc-ar'
AUTOCONF=''
AUTOHEADER=''
AUTOMAKE=''
AWK=''
BUILD_REDIRECTOR_FALSE=''
BUILD_REDIRECTOR_TRUE=''
BUILD_WINCOMPAT_FALSE=''
BUILD_WINCOMPAT_TRUE=''
CC='ccache_cc'
CCDEPMODE=''
CFLAGS='-Os -pipe -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-var
iable '
CPP=''
CPPFLAGS='-I/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/usr/include -I/root/OpenWrt-SDK
-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86
_64_uClibc-0.9.33.2/include -I/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uCli
bc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.
33.2/usr/include -I/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2
.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/includ
e '
CYGPATH_W=''
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
FGREP=''
GREP=''
INET_NTOP_LIB=''
INSTALL_DATA=''
INSTALL_PROGRAM=''
INSTALL_SCRIPT=''
INSTALL_STRIP_PROGRAM=''
LD='x86_64-openwrt-linux-uclibc-ld'
LDFLAGS='-L/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x
86_64/staging_dir/target-x86_64_uClibc-0.9.33.2/usr/lib -L/root/OpenWrt-SDK-15.0
5-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-x86_64_u
Clibc-0.9.33.2/lib -L/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33
.2.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/usr/
lib -L/root/OpenWrt-SDK-15.05-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64
/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/lib '
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAINT=''
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE=''
MAKEINFO=''
MANIFEST_TOOL=''
MKDIR_P=''
NM='x86_64-openwrt-linux-uclibc-gcc-nm'
NMEDIT=''
OBJDUMP='x86_64-openwrt-linux-uclibc-objdump'
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE=''
PACKAGE_BUGREPORT='max.c.lv@gmail.com'
PACKAGE_NAME='shadowsocks-libev'
PACKAGE_STRING='shadowsocks-libev 2.4.5'
PACKAGE_TARNAME='shadowsocks-libev'
PACKAGE_URL=''
PACKAGE_VERSION='2.4.5'
PATH_SEPARATOR=':'
PTHREAD_CC=''
PTHREAD_CFLAGS=''
PTHREAD_LIBS=''
RANLIB='x86_64-openwrt-linux-uclibc-gcc-ranlib'
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP='x86_64-openwrt-linux-uclibc-strip'
USE_SYSTEM_SHARED_LIB_FALSE=''
USE_SYSTEM_SHARED_LIB_TRUE=''
VERSION=''
ac_ct_AR=''
ac_ct_CC=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include=''
am__isrc=''
am__leading_dot=''
am__nodep=''
am__quote=''
am__tar=''
am__untar=''
ax_pthread_config=''
bindir='/usr/bin'
build='x86_64-redhat-linux'
build_alias='x86_64-redhat-linux'
build_cpu=''
build_os=''
build_vendor=''
datadir='/usr/share'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='/usr'
host='x86_64-openwrt-linux'
host_alias='x86_64-openwrt-linux'
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='/usr/info'
install_sh=''
libdir='${exec_prefix}/lib'
libexecdir='/usr/lib'
localedir='${datarootdir}/locale'
localstatedir='/var'
mandir='/usr/man'
mkdir_p=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr'
program_transform_name='s,x,x,'
prefix='/usr'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='/usr/sbin'
sharedstatedir='${prefix}/com'
subdirs=''
sysconfdir='/etc'
target_alias='x86_64-openwrt-linux'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "shadowsocks-libev"
#define PACKAGE_TARNAME "shadowsocks-libev"
#define PACKAGE_VERSION "2.4.5"
#define PACKAGE_STRING "shadowsocks-libev 2.4.5"
#define PACKAGE_BUGREPORT "max.c.lv@gmail.com"
#define PACKAGE_URL ""

configure: exit 77
`

**Comment by allenkey666** [comment]
参考最新的编译教程
