### ISSUE TITLE
请帮助编译个14.07版本的,本人路由器版本是网件3800,安装的是明月永在的五一版本,OPENWRT版本是14.07

### ISSUE THREAD

**Issue by dlonzyz** [bettermanbao/openwrt-shadowsocksR-libev-full#6]
请帮助编译个14.07版本的,本人路由器版本是网件3800,安装的是明月永在的五一版本,OPENWRT版本是14.07,装了15.05版本"全局设置"\"UDP转发"\"访问控制"都显示"尚无任何配置".先谢了.

**Comment by dlonzyz** [comment]
固件版本:
OpenWrt Barrier Breaker 14.07 r45620 五一版 by明月永在

**Comment by allenkey666** [comment]
因为第三方固件存在太多不确定性，尤其是其他集成ss的固件。所以目前一键安装包不支持第三方固件，请理解。
