### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by feijihong** [bettermanbao/openwrt-shadowsocksR-libev-full#65]
我是新手,使用的是虚拟机,系统是ubuntu16.04LTS 64位
SDK是:OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64
安装好所有需要的东西.
前面一切都正常
到最后一步make package/shadowsocksR-libev-full/compile V=s

feijihong@4741G:~/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64$ make package/shadowsocksR-libev-full/compile V=s
#
# configuration written to .config
#
make[1]: Entering directory '/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'
make[2]: Entering directory '/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/package/shadowsocksR-libev-full'
mkdir -p /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/dl
echo "Checking out files from the git repository..."; mkdir -p /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/tmp/dl && cd /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/tmp/dl && rm -rf shadowsocksR-libev-2.5.6 && [ \! -d shadowsocksR-libev-2.5.6 ] && git clone https://github.com/breakwa11/shadowsocks-libev.git shadowsocksR-libev-2.5.6 --recursive && (cd shadowsocksR-libev-2.5.6 && git checkout db893a526e03b43350a6098a2652968dd768a564 && git submodule update) && echo "Packing checkout..." && rm -rf shadowsocksR-libev-2.5.6/.git && 	tar czf /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/tmp/dl/shadowsocksR-libev-2.5.6-1pre.tar.gz shadowsocksR-libev-2.5.6 && mv /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/tmp/dl/shadowsocksR-libev-2.5.6-1pre.tar.gz /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/dl/ && rm -rf shadowsocksR-libev-2.5.6; 
Checking out files from the git repository...
Cloning into 'shadowsocksR-libev-2.5.6'...
remote: Counting objects: 9789, done.
remote: Total 9789 (delta 0), reused 0 (delta 0), pack-reused 9789
Receiving objects: 100% (9789/9789), 8.39 MiB | 3.44 MiB/s, done.
Resolving deltas: 100% (6405/6405), done.
Checking connectivity... done.
Note: checking out 'db893a526e03b43350a6098a2652968dd768a564'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at db893a5... server_def move to common.h
Packing checkout...
. /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/shell.sh; gzip -dc /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/dl/shadowsocksR-libev-2.5.6-1pre.tar.gz | tar -C /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/.. -xf - 
touch /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/.prepared_9eb9c7ef170d7ae4c27da6934851a17e
rm -f /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.shadowsocksR-libev.openssl_installed
(cd /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6; rm -f aclocal.m4; if [ -f ./configure.ac ] || [ -f ./configure.in ]; then [ -d ./autom4te.cache ] && rm -rf autom4te.cache; [ -e ./config.rpath ] || ln -s /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/scripts/config.rpath ./config.rpath; touch NEWS AUTHORS COPYING ABOUT-NLS ChangeLog; AUTOM4TE=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/autom4te AUTOCONF=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/autoconf AUTOMAKE=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/automake ACLOCAL=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/aclocal AUTOHEADER=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/autoheader LIBTOOLIZE=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/libtoolize LIBTOOL=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/libtool M4=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/m4 AUTOPOINT=true /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/autoreconf -v -f -i -s -B /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/share/aclocal -I /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/host/share/aclocal -I /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/share/aclocal -I m4 -I . . || true; fi; );
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/aclocal -I /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/host/share/aclocal -I /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/share/aclocal -I m4 -I . --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory libsodium to autoreconf
autoreconf: Entering directory `libsodium'
autoreconf: running: /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/libtoolize --force
OpenWrt-libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
OpenWrt-libtoolize: linking file `build-aux/ltmain.sh'
OpenWrt-libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
OpenWrt-libtoolize: linking file `m4/libtool.m4'
OpenWrt-libtoolize: linking file `m4/ltoptions.m4'
OpenWrt-libtoolize: linking file `m4/ltsugar.m4'
OpenWrt-libtoolize: linking file `m4/ltversion.m4'
OpenWrt-libtoolize: linking file `m4/lt~obsolete.m4'
autoreconf: running: /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/autoconf --include=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/host/share/aclocal --include=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/share/aclocal --include=m4 --include=. --prepend-include=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/share/aclocal --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/automake --add-missing --force-missing
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/automake line 3938.
configure.ac:150: installing 'build-aux/compile'
autoreconf: Leaving directory `libsodium'
OpenWrt-libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `auto'.
OpenWrt-libtoolize: linking file `auto/ltmain.sh'
OpenWrt-libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
OpenWrt-libtoolize: linking file `m4/libtool.m4'
OpenWrt-libtoolize: linking file `m4/ltoptions.m4'
OpenWrt-libtoolize: linking file `m4/ltsugar.m4'
OpenWrt-libtoolize: linking file `m4/ltversion.m4'
OpenWrt-libtoolize: linking file `m4/lt~obsolete.m4'
autoreconf: running: /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/autoheader --include=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/host/share/aclocal --include=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/share/aclocal --include=m4 --include=. --prepend-include=/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/share/aclocal --force
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/automake line 3938.
autoreconf: Leaving directory `.'
(cd /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/./; if [ -x ./configure ]; then find /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/ -name config.guess | xargs -r chmod u+w; find /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/ -name config.guess | xargs -r -n1 cp --remove-destination /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/scripts/config.guess; find /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/ -name config.sub | xargs -r chmod u+w; find /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/ -name config.sub | xargs -r -n1 cp --remove-destination /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/scripts/config.sub; AR="mipsel-openwrt-linux-uclibc-gcc-ar" AS="ccache_cc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float" LD=mipsel-openwrt-linux-uclibc-ld NM="mipsel-openwrt-linux-uclibc-gcc-nm" CC="ccache_cc" GCC="ccache_cc" CXX="ccache_cxx" RANLIB="mipsel-openwrt-linux-uclibc-gcc-ranlib" STRIP=mipsel-openwrt-linux-uclibc-strip OBJCOPY=mipsel-openwrt-linux-uclibc-objcopy OBJDUMP=mipsel-openwrt-linux-uclibc-objdump SIZE=mipsel-openwrt-linux-uclibc-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float " CPPFLAGS="-I/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -I/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/include -I/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib -L/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/lib -L/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib "   ./configure --target=mipsel-openwrt-linux --host=mipsel-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls   --disable-ssp ; fi; )
configure: loading site script /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/site/mipsel
checking for mipsel-openwrt-linux-gcc... ccache_cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether ccache_cc accepts -g... yes
checking for ccache_cc option to accept ISO C89... none needed
checking whether ccache_cc understands -c and -o together... yes
checking how to run the C preprocessor... ccache_cc -E
checking for grep that handles long lines and -e... /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/grep
checking for egrep... /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for mipsel-openwrt-linux-strip... mipsel-openwrt-linux-uclibc-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of ccache_cc... gcc3
checking for mipsel-openwrt-linux-ar... mipsel-openwrt-linux-uclibc-gcc-ar
checking the archiver (mipsel-openwrt-linux-uclibc-gcc-ar) interface... ar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... mipsel-openwrt-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/sed
checking for fgrep... /home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/host/bin/grep -F
checking for ld used by ccache_cc... mipsel-openwrt-linux-uclibc-ld
checking if the linker (mipsel-openwrt-linux-uclibc-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... mipsel-openwrt-linux-uclibc-gcc-nm
checking the name lister (mipsel-openwrt-linux-uclibc-gcc-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to mipsel-openwrt-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for mipsel-openwrt-linux-uclibc-ld option to reload object files... -r
checking for mipsel-openwrt-linux-objdump... mipsel-openwrt-linux-uclibc-objdump
checking how to recognize dependent libraries... pass_all
checking for mipsel-openwrt-linux-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for mipsel-openwrt-linux-ar... (cached) mipsel-openwrt-linux-uclibc-gcc-ar
checking for archiver @FILE support... @
checking for mipsel-openwrt-linux-strip... (cached) mipsel-openwrt-linux-uclibc-strip
checking for mipsel-openwrt-linux-ranlib... mipsel-openwrt-linux-uclibc-gcc-ranlib
checking command to parse mipsel-openwrt-linux-uclibc-gcc-nm output from ccache_cc object... ok
checking for sysroot... no
checking for mipsel-openwrt-linux-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if ccache_cc supports -fno-rtti -fno-exceptions... no
checking for ccache_cc option to produce PIC... -fPIC -DPIC
checking if ccache_cc PIC flag -fPIC -DPIC works... yes
checking if ccache_cc static flag -static works... yes
checking if ccache_cc supports -c -o file.o... yes
checking if ccache_cc supports -c -o file.o... (cached) yes
checking whether the ccache_cc linker (mipsel-openwrt-linux-uclibc-ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... cross
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for pcre-config... no
checking for pcre location... not found
**## **configure: error: Cannot find pcre library. Configure --with-pcre=DIR
Makefile:207: recipe for target '/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/.configured_yyn' failed
make[2]: *** [/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/shadowsocksR-libev-openssl/shadowsocksR-libev-2.5.6/.configured_yyn] Error 1
make[2]: Leaving directory '/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/package/shadowsocksR-libev-full'
package/Makefile:191: recipe for target 'package/shadowsocksR-libev-full/compile' failed
make[1]: *** [package/shadowsocksR-libev-full/compile] Error 2
make[1]: Leaving directory '/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'
/home/feijihong/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/toplevel.mk:174: recipe for target 'package/shadowsocksR-libev-full/compile' failed
make: *** [package/shadowsocksR-libev-full/compile] Error 2****

看起来像是后面这段出错了,网上搜了好多,都不知道怎么处理.

**Comment by feijihong** [comment]
# 选择要编译的包 Network -> shadowsocksr-libev
make menuconfig

选择是按Y吗??其他默认不管是吗?
我是新手,希望能多多指教.谢谢!

**Comment by feijihong** [comment]
看到几个关键字
git checkout -b
Cannot find pcre library. 
然后下面几个错误

但是具体操作就一头雾水- -

**Comment by planktonzp** [comment]
同问 如果方便希望大神能帮忙稍微讲一下 谢谢

**Comment by moralrebuild** [comment]
编译错误，刚开始时asciidoc，这个在Debian下都有1GB的编译空间。注释掉，还有如下错误。无解。现在这个项目还有维护吗？

Package shadowsocksr-libev is missing dependencies for the following libraries:
libpcre.so.1
libz.so.1

**Comment by nmapleaf** [comment]
@moralrebuild 编辑Makefile增加相关依赖就行了

**Comment by moralrebuild** [comment]
@nmapleaf 可以具体说明一下吗？谢谢，另外我理解Makefile是完整项目不可分割，为什么没有来维护修改呢。感觉这个这个项目已经自暴自弃了。

**Comment by allenkey666** [comment]
最近在忙别的事情，过阵子更新一下吧。

**Comment by nmapleaf** [comment]
@moralrebuild DEPENDS:=+libopenssl +libpthread +libpcre 我是编译的时候提示缺少libpcre.so.1所以加上依赖就编译通过了

**Comment by moralrebuild** [comment]
@bettermanbao @nmapleaf 多谢二位及时回复！话语不当之处还请海涵！哈哈

**Comment by allenkey666** [comment]
你的心情我理解，没办法，生出来就要管嘛。

**Comment by cutecamel** [comment]
@moralrebuild 感谢指导，编译成功。

**Comment by cutecamel** [comment]
@nmapleaf 感谢指导，编译成功。@bettermanbao 个人感觉你的版本好，不需要服务端开UDP

**Comment by allenkey666** [comment]
@cutecamel
目前的版本是需要服务器端开udp支持的，不想用udp可以通过安装pdnsd将dns查询转化成tcp。

**Comment by moralrebuild** [comment]
在LEDE 17.01.1上，还是有错误：
	checking for cipher_init_ctx in -lpolarssl... no
	configure: error: PolarSSL libraries not found.
	Makefile:207: recipe for target '/home/col/lede/build_dir/target-mips_24kc_musl-1.1.16/shadowsocksR-libev-polarssl/shadowsocksR-libev-2.5.6/.configured_yyyyyyy' failed

**Comment by nmapleaf** [comment]
@moralrebuild LEDE上没有PolarSSL了，这个项目改名了，现在叫mbedtls，你编译openssl的版本吧，把polarSSL的版本去掉就行了，或者你可以试试把依赖改成libmbedtls试试

**Comment by allenkey666** [comment]
今天在CC下编译成功，目前上游还在修复ssr-tunnel的问题。等修复后会发送一个release，包含ar71xx和ramips的ipk。

**Comment by moralrebuild** [comment]
@nmapleaf 谢谢你的提示。我原本选择的是shadowsocksr-libev-gfwlist-4M， 想尝试在LEDE高版本内核上为WR703N(手头有几个没有改8M/16M的存货）编译一个在原生版的固件

**Comment by moralrebuild** [comment]
最新的版本在openwrt 15.05 上编译出错：
install: cannot stat '/home/col/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocksR-libev-polarssl/shadowsocksR-libev-v20170514/src/ss-tunnel': No such file or directory

**Comment by allenkey666** [comment]
上游代码还在修复ss-tunnel的问题，不要急。
最新版的ss-redir和ss-local，你如果需要，在附件里。

[shadowsocksr-libev_v20170514-1pre_ar71xx.zip](https://github.com/bettermanbao/openwrt-shadowsocksR-libev-full/files/1003388/shadowsocksr-libev_v20170514-1pre_ar71xx.zip)

**Comment by allenkey666** [comment]
编译教程已更新，坑都填好了。

**Comment by unflypig** [comment]
你好，请问lede编译$$的教程在哪里？谢谢 @bettermanbao

**Comment by allenkey666** [comment]
@unflypig 首页readme
