### ISSUE TITLE
auth_chain_a  does not work after compiling in lede

### ISSUE THREAD

**Issue by jack338c** [bettermanbao/openwrt-shadowsocksR-libev-full#67]
everything looks fine but it just does not work in my router 4300(auth_chain_a on pc is ok under same sever ip )
but  auth_aes128_md5  works ok

any ideas?
thank you Jacky

**Comment by allenkey666** [comment]
not test latest version with auth_aes128_md5, have you tried ssr-local?

**Comment by jack338c** [comment]
@bettermanbao 
I did not test ssr-local,currently only use ssr-redir +pdnsd
needs your help my friend

**Comment by jack338c** [comment]
also find another issue: if I use auth_aes128_md5 and tls1.2_ticket_auth of the newest ssr on lede.the system log on router will be the following .and some website can not be opened
I'm not sure this is only happend on my router  or not.

Thu May 18 08:21:56 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:21:56 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:21:56 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:21:56 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:21:58 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:21:58 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:21:58 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:21:58 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:02 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:02 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:02 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:02 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:02 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:02 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:02 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:02 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:04 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:04 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:15 2017 kern.err /usr/bin/ssr-redir[21997]: server recv: Connection reset by peer
Thu May 18 08:22:19 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:19 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:20 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:20 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:20 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:20 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:30 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:30 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt
Thu May 18 08:22:42 2017 kern.err /usr/bin/ssr-redir[13749]: post_decrypt wrong HMAC
Thu May 18 08:22:42 2017 kern.err /usr/bin/ssr-redir[13749]: client_post_decrypt

**Comment by allenkey666** [comment]
it's better to post this info to origin ssr repo for help.

**Comment by jack338c** [comment]
ok.thank you @bettermanbao

**Comment by jack338c** [comment]
auth_chain_a  works now @bettermanbao
