### ISSUE TITLE
ssr-watchdog不能正常工作，因为ping不支持'-c'参数

### ISSUE THREAD

**Issue by moralrebuild** [bettermanbao/openwrt-shadowsocksR-libev-full#68]
关闭 IPv6后编译openwrt 15.05.01，运行时发现ssr-watchdog脚本不断报错：

2017-05-23 02:30:53] Backup server is running.
ping: bad address '-c'
sh: bad number
[2017-05-23 02:30:53] Main server down,% packet loss.
[2017-05-23 02:30:53] No problem.
[2017-05-23 02:40:01] Backup server is running.
ping: bad address '-c'
sh: bad number
[2017-05-23 02:40:01] Main server down,% packet loss.
[2017-05-23 02:40:01] No problem.

**Comment by allenkey666** [comment]
我准备把这个backup server功能去掉了

**Comment by moralrebuild** [comment]
那有点可惜了啊，有替代性的高可靠性方案吗？

**Comment by moralrebuild** [comment]
找到一个方案了，去掉busybox内置的ping, 在Network下勾选iputils-ping，后者是个功能比较完整的ping,  支持-c count参数
  Network 
    <*> iputils-ping.............................................. iputils - ping

**Comment by allenkey666** [comment]
为什么我的busybox ping支持-c？
bb cc lede都支持

**Comment by laincat** [comment]
ssr-watchdog 测试链接可以改为可设置吗？

**Comment by allenkey666** [comment]
你自己改一下不就可以了？

**Comment by laincat** [comment]
呃，也对，哈哈哈，想说方便大家哈。。。(感谢大大的所有///。///
