### ISSUE TITLE
 v20170521版提供LuCI了？同时也放弃提供gfwlist白名单翻墙？

### ISSUE THREAD

**Issue by moralrebuild** [bettermanbao/openwrt-shadowsocksR-libev-full#69]
感谢作者辛苦奉献时间来更新SSR支持上游最新发布的混淆协议。但是感觉放弃LuCI会使它变成一个完全不同的项目，而且失去对入门级使用者的吸引力。但愿是我的误读。

**Comment by allenkey666** [comment]
因为上游禁用了ss-tunnel，所以gfwlist版的代码需要一些修改。
随后会放出，不用担心。

**Comment by moralrebuild** [comment]
太好了，期待！

**Comment by allenkey666** [comment]
GFWList版已更新，LEDE 17.01下测试通过。
