### ISSUE TITLE
gfwlist 依赖 kernel版本？

### ISSUE THREAD

**Issue by bash99** [bettermanbao/openwrt-shadowsocksR-libev-full#70]
在octeon的14.07上安装
root@Gargoyle:~# opkg install shadowsocksr-libev-gfwlist_v20170521-1pre_octeon.ipk dns-forwarder_1.2.0-1_octeon.ipk
Installing shadowsocksr-libev-gfwlist (v20170521-1pre) to root...
Installing dns-forwarder (1.2.0-1) to root...
Configuring dns-forwarder.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocksr-libev-gfwlist:
 * 	kernel (= 3.10.49-1-b716600778d8f69d2e3d89c32effdfe5) * 
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-gfwlist.

只安装shadowsocksr-libev_v20170521-1pre_octeon.ipk是没问题的，而且ss-local也能正常运行

**Comment by bash99** [comment]
用--force-depends  --force-overwrite强行装上了，但是有个小错
//usr/lib/opkg/info/shadowsocksr-libev-gfwlist.postinst: line 7: /etc/init.d/dns-forarder: not found

“dns-forarder” ?
感觉是脚本写错了

**Comment by allenkey666** [comment]
kernel问题是你编译用的sdk和你的固件不匹配造成的
dns-forward漏写了w，不过这个不影响使用。

**Comment by bash99** [comment]
强行装上倒是都能用，但是 shadowsocksr-libev 就不依赖kernel 版本，这个是为啥？

**Comment by allenkey666** [comment]
可能某些依赖会牵扯到内核吧，比如ipset iptables
