### ISSUE TITLE
v20170521此次更新的无法在潘多拉上安装

### ISSUE THREAD

**Issue by BigFF** [bettermanbao/openwrt-shadowsocksR-libev-full#71]
此次更新的无法在潘多拉上进行安装，是否此次更新只能安装在LEDE上？
等更新ssr到新版，一些旧的协议ssr后续删除了，还有新增的协议

**Comment by allenkey666** [comment]
pandorabox用openwrt 14.04的sdk编译后，可以运行。
Release里的ipk是lede的。
但是ssr-watchdog里wget的参数需要修改一下。

**Comment by cha331** [comment]
pkg install /tmp/shadowsocksr-libev-gfwlist_v20170521-1pre_mipsel_24kc.ipk
Installing shadowsocksr-libev-gfwlist (v20170521-1pre) to root...
Collected errors:
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /etc/config/dns-forwarder
	But that file is already provided by package  * dns-forwarder
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /etc/dnsmasq.conf
	But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /etc/firewall.user
	But that file is already provided by package  * firewall
自己编译的lede，一直报错
