### ISSUE TITLE
lede编译时报错

### ISSUE THREAD

**Issue by cha331** [bettermanbao/openwrt-shadowsocksR-libev-full#72]
pkg install /tmp/shadowsocksr-libev-gfwlist_v20170521-1pre_mipsel_24kc.ipk
Installing shadowsocksr-libev-gfwlist (v20170521-1pre) to root...
Collected errors:
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /etc/config/dns-forwarder
	But that file is already provided by package  * dns-forwarder
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /etc/dnsmasq.conf
	But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /etc/firewall.user
	But that file is already provided by package  * firewall
我试了下用scp传上去直接安装也是这个错误

**Comment by cha331** [comment]
Collected errors:
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /home/kai/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/config/dns-forwarder
	But that file is already provided by package  * dns-forwarder
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /home/kai/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/dnsmasq.conf
	But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /home/kai/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/firewall.user
	But that file is already provided by package  * firewall
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-gfwlist.
 * pkg_alternatives_update_path: failed symlinking /home/kai/lede/build_dir/target-mipsel_24kc_musl/root-ramips/sbin/ip -> /sbin/ip-tiny
package/Makefile:64: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/kai/lede'
package/Makefile:106: recipe for target '/home/kai/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install' failed
make[1]: *** [/home/kai/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/kai/lede'
/home/kai/lede/include/toplevel.mk:206: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by allenkey666** [comment]
https://github.com/bettermanbao/lede/commit/02e7a2e258898572e6a46ba3942a28b4a8e37bd6
