### ISSUE TITLE
建议在shadowsocksR-libev-gfwlist中加入ssr-local

### ISSUE THREAD

**Issue by BzLfJ6fgxJ4R** [bettermanbao/openwrt-shadowsocksR-libev-full#73]
有不少时候需要路由器提供SOCKS代理，方便很多程序设置，现在这个安装完之后应该是无法单独添加ssr-local的吧？
希望能在以后加入:)

**Comment by allenkey666** [comment]
直接复制一个ssr-local进去就可以运行了，下一版考虑加入吧。
主要是我那蛋疼的路由器只有4M flash，刷lede后没有空间放ssr-local了，所以只留下了ssr-redir。

**Comment by BzLfJ6fgxJ4R** [comment]
复制进去能用，竟然还有这种操作。
这个大小我服的233

**Comment by hoolinoo** [comment]
换个好点的路由器啊。或者硬改
