### ISSUE TITLE
Recommend dnsproxy or pdnsd instead of DNS-Forwarder

### ISSUE THREAD

**Issue by jack338c** [bettermanbao/openwrt-shadowsocksR-libev-full#74]
DNS-Forwarder can not play videos on some website
for example: https://www.tube8.com/  https://www.pornhub.com/  ..etc
but dnsproxy or pdnsd can
thank you :)

**Comment by allenkey666** [comment]
will test if its dns-forwarder issue

**Comment by jack338c** [comment]
and here is the dnsproxy source
https://github.com/vietor/dnsproxy
https://github.com/zhengxinhn/dnsproxy
Could you try compile this to openwrt-shadowsocksR-libev-full if you have spare time .it's faster than pdnsd and DNS-Forwarder 
it work in padavan ssr very well

**Comment by jack338c** [comment]
software cause conflict,it's my router problem
Sorry and thanks for your time

**Comment by jack338c** [comment]
sorry,the issue did not solve yet,still can 't play a lot of videos,but use 7620老毛子Padavan is ok

**Comment by jack338c** [comment]
the reason is the url of videos bypass ss,so whitelist is ok 
and I find dnsforwarder is faster than pdnsd.

**Comment by allenkey666** [comment]
tested just now, you are right.
The video domain was not covered by gfwlist. Both pdnsd and dns-forwarder cannot play it.
You may try to find these domain by yourself, then add it to custom list.

**Comment by jack338c** [comment]
yeah,I got it,thank you !
