### ISSUE TITLE
No feed for package 'libmbedtls' found

### ISSUE THREAD

**Issue by yangxuan8282** [bettermanbao/openwrt-shadowsocksR-libev-full#75]
```
openwrt@abbfe0f4b6ca:~/sdk$ ./scripts/feeds install libmbedtls
WARNING: No feed for package 'libmbedtls' found, maybe it's already part of the standard packages?
```

我是在用 OpenWrt-SDK-15.05.1-ramips-mt7620 的 docker 编译时候遇到这个问题的，不知道是不是 openwrt 下没有这个包，另外想问下编译出来的包是都需要装吗，还是选择性的装一部分

**Comment by allenkey666** [comment]
mbedtls是lede下的lib，cc下是polarssl。
一般用户建议安装openssl的版本，也就是没有后缀的。

dns-forwarder需要手动装。
如果要用mbedtls版，mbedtls也要手动装。
