### ISSUE TITLE
安装没有出现Services

### ISSUE THREAD

**Issue by WonJiu** [bettermanbao/openwrt-shadowsocksR-libev-full#76]
root@LEDE:~# opkg install shadowsocksr-libev-mbedtls_v20170601-1pre_mipsel_24kc.ipk --force-overwrite
Installing shadowsocksr-libev-mbedtls (v20170601-1pre) to root...
Configuring shadowsocksr-libev-mbedtls.
root@LEDE:~# 

软件包管理已经能找到这个包已安装，没有找到设置入口。哪里出问题了？K2 LEDE17.01正式版

**Comment by allenkey666** [comment]
只有gfwlist版的ipk带luci界面。
