### ISSUE TITLE
新版本在极路由4下无法运行，使用的是ramips

### ISSUE THREAD

**Issue by ghost** [bettermanbao/openwrt-shadowsocksR-libev-full#78]
感谢跟进更新，很可惜新发布的版本在极路由4下无法运行。
现在本人可以用的最高版本是[EvansMike](https://plus.google.com/+EvansMike)发布的2.4.8版。
另外gfwlist使用[Cokebar Chi](https://github.com/cokebar/gfwlist2dnsmasq)的脚本，自动更新，不用python。

**Comment by allenkey666** [comment]
最新版仅提供lede的ipk, openwrt需要自己编译。
