### ISSUE TITLE
999-tweak-config-for-shadowsocks.patch不存在

### ISSUE THREAD

**Issue by jianbiaoxu** [bettermanbao/openwrt-shadowsocksR-libev-full#79]
https://github.com/bettermanbao/lede/raw/lede-17.01/package/libs/mbedtls/patches/999-tweak-config-for-shadowsocks.patch

这个报404。

**Comment by allenkey666** [comment]
fixed.

https://github.com/bettermanbao/lede/raw/lede-17.01.2/package/libs/mbedtls/patches/999-tweak-config-for-shadowsocks.patch
