### ISSUE TITLE
有OP安装方法码

### ISSUE THREAD

**Issue by JinLong-Huang** [bettermanbao/openwrt-shadowsocksR-libev-full#81]
有OP安装方法码 捣鼓好几天没装上

**Comment by allenkey666** [comment]
op需要自己编译ipk

**Comment by knlvz** [comment]
你好，你那个openwrt-shadowsocks-libev-full还更新吗？想应用在LEDE上，无法编译IPK，请教下按照原来从openwrt编译的步骤外，需要什么步骤？

**Comment by allenkey666** [comment]
首页下面的编译教程就是lede的，照做就可以了。
