### ISSUE TITLE
1MB/s 流量以上 CPU占用高

### ISSUE THREAD

**Issue by F-TD5X** [bettermanbao/openwrt-shadowsocksR-libev-full#82]
Device: TP-Link WR841N V7 64MB RAM 32MB ROM USB
Config:
- config没有开启混淆和加密
- 启动脚本加入了 -u 试图开启UDP转发

Detail:
- 当通过代理的流量达到1MB/s 以上后， ssr-redir CPU占用就达到100%，内存占用5%

**Comment by allenkey666** [comment]
加密方式改rc4-md5，混淆和协议都不用，再试试。
