### ISSUE TITLE
cannot compile it now

### ISSUE THREAD

**Issue by mrcuilin** [bettermanbao/openwrt-shadowsocksR-libev-full#84]
For the reason that the brkwal had removed his/her source. How to?

**Comment by wuzhongyi1105** [comment]
I have a copy on my laptop computer but the computer is in my school. I will upload to github when I go back to school.

**Comment by allenkey666** [comment]
https://github.com/bettermanbao/openwrt-shadowsocksR-libev-full/releases/download/v20170613/shadowsocksR-libev-v20170613-1pre.tar.gz
