### ISSUE TITLE
编译缺少安装包

### ISSUE THREAD

**Issue by raink** [bettermanbao/openwrt-shadowsocksR-libev-full#86]
求教，make menuconfig 中选择了 dnsmasq，同时也选择了 dnsmasq-full，提示如下：
--------------------------------------------------------
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package dnsmasq-full.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocksr-libev-gfwlist:
 * 	dns-forwarder * 
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-gfwlist.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package dnsmasq-full.
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/etc/firewall.user
	But that file is already provided by package  * firewall
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-gfwlist.
package/Makefile:64: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/root/source'
package/Makefile:106: recipe for target '/home/root/source/staging_dir/target-mips_24kc_musl/stamp/.package_install' failed
make[1]: *** [/home/root/source/staging_dir/target-mips_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/root/source'
/home/root/source/include/toplevel.mk:207: recipe for target 'world' failed
make: *** [world] Error 2

如果只选择 dnsmasq-full，不选择 dnsmasq，则提示：

 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocksr-libev-gfwlist:
 * 	dns-forwarder * 
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-gfwlist.
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/etc/dnsmasq.conf
	But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package shadowsocksr-libev-gfwlist wants to install file /home/root/source/build_dir/target-mips_24kc_musl/root-ar71xx/etc/firewall.user
	But that file is already provided by package  * firewall
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-gfwlist.
package/Makefile:64: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/root/source'
package/Makefile:106: recipe for target '/home/root/source/staging_dir/target-mips_24kc_musl/stamp/.package_install' failed
make[1]: *** [/home/root/source/staging_dir/target-mips_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/root/source'
/home/root/source/include/toplevel.mk:207: recipe for target 'world' failed
make: *** [world] Error 2

使用的是最新的开发包，以及下载了 shadowsocksR-libev-v20170613-1pre.tar.gz

**Comment by allenkey666** [comment]
https://github.com/bettermanbao/lede/commit/02e7a2e258898572e6a46ba3942a28b4a8e37bd6
