### ISSUE TITLE
MBEDTLS_CAMELLIA_C required

### ISSUE THREAD

**Issue by raink** [bettermanbao/openwrt-shadowsocksR-libev-full#87]
编译固件时，选择 shadowsocksr-libev-gfwlist-mbedtls 提示如下错误，请帮忙看看如何处理，谢谢！

checking whether mbedtls supports the Camellia block cipher or not... configure: error: MBEDTLS_CAMELLIA_C required
Makefile:170: recipe for target '/home/root/source/build_dir/target-mips_24kc_musl-1.1.16/shadowsocksR-libev-mbedtls/shadowsocksR-libev-v20170613/.configured_yyyyyyyn' failed
make[3]: *** [/home/root/source/build_dir/target-mips_24kc_musl-1.1.16/shadowsocksR-libev-mbedtls/shadowsocksR-libev-v20170613/.configured_yyyyyyyn] Error 1
make[3]: Leaving directory '/home/root/source/package/shadowsocksR-libev-full'

**Comment by allenkey666** [comment]
你们难道都不看readme的吗？？？

wget -P package/feeds/base/mbedtls/patches https://github.com/bettermanbao/lede/raw/lede-17.01.2/package/libs/mbedtls/patches/999-tweak-config-for-shadowsocks.patch

**Comment by raink** [comment]
按照教程是wget了补丁，但是在编译的时候还是如此，请指教。
